import pprint
import json

pf = pprint.PrettyPrinter(width=41, compact=True).pformat

DATA = "_data/site-manifest.json"


class StorkFileItem:
    def __init__(
            self,
            path: str,
            url: str,
            title: str,
            ):
        self.path = path
        self.url = url
        self.title = title

    def to_dict(self) -> dict:
        return {
            "path": self.path,
            "url": self.url,
            "title": self.title,
        }


StorkFileList = list[dict]  # type alias


class StorkConfigRaw:
    def __init__(
            self,
            base_directory: str,
            url_prefix: str,
            files: StorkFileList,
            output_filename: str,
            debug=False,  # type: bool
            ):
        self.base_directory = base_directory  # type: str
        self.url_prefix = url_prefix  # type: str
        self.files = files  # type: StorkFileList

        self.output_filename = output_filename  # type: str
        self.debug = debug  # type: bool


class StorkToml:
    def new(c: StorkConfigRaw) -> str:
        assert(
            c.base_directory and
            c.url_prefix and
            c.files and
            c.output_filename and
            isinstance(c.debug, bool)
        )
        return f"""# Generated from {__name__}

[input]
base_directory = \"{c.base_directory}\"
url_prefix = \"{c.url_prefix}\"
files = {c.files}

[output]
filename = \"{c.output_filename}\"
debug = {c.debug}
"""


def parse_sitmanifest(data: dict) -> StorkConfigRaw:
    """
    Specifically for parsing site-manifest.json files
    generated by https://gitlab.com/opendevise/oss/antora-site-generator-ms

    We expect the data loaded with
    ``json.load("site-manifest.json")``
    to be structured like this:

        ..  code-block:: javascript

            {
                \"version\": 3,
                \"generated\": 1611367477126,
                \"url\": \"http://localhost\",
                \"components\": [
                    {
                    \"name\": \"TD2020-demo\",
                    \"title\": \"TD2020 demo\",
                    \"latest\": \"0.1.0\",
                    \"versions\": [
                        {
                        \"version\": \"0.1.0\",
                        \"url\": \"/TD2020-demo/0.1.0/index.html\",
                        \"pages\": [
                            {
                            \"module\": \"about-eiq-platform\",
                            \"path\": \"about-platform-ui.adoc\",
                            \"url\":\
\"/TD2020-demo/0.1.0/about-eiq-platform/about-platform-ui.html\",
                        \"title\":\
\"About the platform&#8217;s user interface\"
                            },
                            //...
                            ]
                        }]
                    }
                ]
            }

    :param data: dict from ``json.load("site-manifest.json")``.
    :returns: StorkConfigRaw
    """
    file_list = []
    for component in data.get("components"):
        for version in component.get("versions"):
            for page in version.get("pages"):
                file_list.append(
                    StorkFileItem(
                        page.get("path"),
                        page.get("url"),
                        page.get("title")
                        ).to_dict()
                )

    return StorkConfigRaw(
        base_directory="build/site",
        url_prefix=data.get("url"),
        files=file_list,
        output_filename="site-manifest.toml"
    )


if __name__ == "__main__":
    stork = StorkConfigRaw(
        "basedir",
        "urlpref",
        "files",
        "outfile",
        # True
        )

    with open(DATA, "r") as f:
        data = json.load(f)
        f.close()

    parsed_manifest = parse_sitmanifest(data)
    output_toml = StorkToml.new(parsed_manifest)

    with open("output.log", "w") as file:
        file.write(f"{output_toml}")
        file.close()
